---
- name: Zookeeper Setup
  hosts: zookeeper
  gather_facts: True
  remote_user: root
  roles:
    - common
    - zookeeper

- name: Clickhouse Setup
  hosts: clickhouse
  gather_facts: True
  remote_user: root
  roles:
    - common
    - clickhouse
