---
- name: Zookeeper Setup
  hosts: zookeeper
  remote_user: root
  var_files:
    - group_vars/zookeeper
  roles:
    - common
    - zookeeper

- name: Clickhouse Setup
  hosts: clickhouse
  remote_user: root
  var_files:
    - group_vars/clickhouse
  roles:
    - common
    - clickhouse
