---

- hosts: all
  gather_facts: False
  remote_user: root
  become: yes
  become_user: root
  become_method: sudo
  serial: 3

  tasks:
    - name: Install Python 3
      raw: test -e /usr/bin/python || (yum update && yum install -y python3)

    - name: Fancy way of doing authorized_keys
      authorized_key: user=root
                      exclusive=no
                      key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    #- name: Create /root/.ssh
    #  file: path=/root/.ssh state=directory mode=0700

    #- name: Create /root/.ssh/authorized_keys from our local ssh pubkey
    #  lineinfile: dest=/root/.ssh/authorized_keys line="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

